[bot]
token = "1234567890"
creator_id = 1234567890
admin_password = "your_admin_password"

[security]
encode_key = "encode_key"

[database]
host = "localhost"
port = 5432
user = "postgres"
password = "passkey"
database = "trudex"
