"""add group

Revision ID: 520eccd2e55f
Revises: d3bd5df63c1b
Create Date: 2026-01-02 19:42:09.264423

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '520eccd2e55f'
down_revision: str | None = 'd3bd5df63c1b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('number >= 1000 AND number <= 9999', name='check_group_number'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_groups_number'), 'groups', ['number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_groups_number'), table_name='groups')
    op.drop_table('groups')
    # ### end Alembic commands ###
