"""test fix

Revision ID: bec177451434
Revises: a879badde4a5
Create Date: 2026-01-02 21:54:33.772279

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'bec177451434'
down_revision: str | None = 'a879badde4a5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('attempts', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'attempts')
    # ### end Alembic commands ###
