"""test model add password and expires_at fields

Revision ID: d3bd5df63c1b
Revises: f63140aa50c0
Create Date: 2026-01-02 17:05:33.443875

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd3bd5df63c1b'
down_revision: str | None = 'f63140aa50c0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('password', sa.String(length=255), nullable=True))
    op.add_column('tests', sa.Column('expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'expires_at')
    op.drop_column('tests', 'password')
    # ### end Alembic commands ###
