"""add_name_and_group_updated_at

Revision ID: e002f2b802ec
Revises: bec177451434
Create Date: 2026-01-03 15:28:05.112132

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e002f2b802ec'
down_revision: str | None = 'bec177451434'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name_updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('group_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'group_updated_at')
    op.drop_column('users', 'name_updated_at')
    # ### end Alembic commands ###
